.Dd February 11, 2020
.Dt WITH-BORG-LOCK 8
.Os steevie
.Sh NAME
.Nm with-borg-lock
.Nd run a program while holding
.Xr run-borg.lock 5
.Sh SYNOPSIS
.Nm
.Op Fl w
.Ar command
.Op Ar arguments...
.Sh DESCRIPTION
.Nm
atomically acquires
.Xr run-borg.lock 5
and then runs
.Ar command .
The options are as follows:
.Bl -hang
.It Fl w
Instead of exiting when the lock can't be acquired, retry in a loop until success.
.It Cm --
Stop option processing.
.El
.Sh EXIT CODE
.Ex -std
.Sh AUTHORS
.An AJ Jordan Aq Mt alex@strugee.net
.Sh BUGS
.Nm
does not clean up
.Xr run-borg.lock 5
if it is killed.
